  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed sudkul/udagram-api-feed:v0
  - docker tag udagram-api-user sudkul/udagram-api-user:v0
  - docker tag udagram-frontend sudkul/udagram-frontend:v0
  - docker tag udagram-reverseproxy sudkul/udagram-reverseproxy:v0
## Do similar for other three images```
```bash
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sudkul/udagram-api-feed:v0
  - docker push sudkul/udagram-api-user:v0
  - docker push sudkul/udagram-frontend:v0
  - docker push sudkul/udagram-reverseproxy:v0