dist: jammy
language: node_js
node_js:
  - 18

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed chautc/udagram-api-feed:v3
  - docker tag udagram-api-user chautc/udagram-api-user:v3
  - docker tag udagram-frontend chautc/udagram-frontend:v3
  - docker tag udagram-reverseproxy chautc/udagram-reverseproxy:v3

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chautc/udagram-api-feed:v3
  - docker push chautc/udagram-api-user:v3
  - docker push chautc/udagram-frontend:v3
  - docker push chautc/udagram-reverseproxy:v3