apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - image: chautc/udagram-reverseproxy:v4
        name: udagram-reverseproxy
        ports:
        - containerPort: 8080