apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
        api: external        
    spec:
      containers:
      - image: chautc/udagram-frontend:v4
        name: udagram-frontend
        ports:
        - containerPort: 80